DEFAULT                  = "default"
DEFAULT_BUFFER_SIZE      = 4096
DEFAULT_BROADCAST_PORT   = 9444
DEFAULT_ENCODING         = "utf-8"
DEFAULT_PORT             = 1060 
DEFAULT_SERVER_PORT      = 1060
DEFAULT_CLIENT_PORT      = 1060

DEFAULTS = (
    DEFAULT,
    DEFAULT_BUFFER_SIZE,
    DEFAULT_BROADCAST_PORT,
    DEFAULT_ENCODING,
    DEFAULT_PORT,
    DEFAULT_SERVER_PORT,
    DEFAULT_CLIENT_PORT,
)
